### ISSUE TITLE
Header file missing for installation

### ISSUE THREAD

**Issue by slhale** [alexrudy/FTR#3]
When attempting to install FTR I encounter the error 

```
FTR/cextern/libFTR/src/ftr.h:18:19: fatal error: fftw3.h: No such file or directory
 #include <fftw3.h>
                   ^
compilation terminated.
```

If I add an `__init__.py` to the top FTR folder I am able to attempt to run some code, but then I run into this error 

```
Traceback (most recent call last):
  File "phase4.py", line 15, in <module>
    from FTR.FTR.utils import circle_aperture, remove_piston, remove_tiptilt
  File "/home/sarah/Documents/kapao-wavefront/FTR/FTR/__init__.py", line 15, in <module>
    from .ftr import FourierTransformReconstructor
  File "/home/sarah/Documents/kapao-wavefront/FTR/FTR/ftr.py", line 32, in <module>
    from .libftr._ftr import CFTRBase
ImportError: No module named _ftr
```

which I believe is from the failed install.

**Comment by alexrudy** [comment]
This looks like you are missing a development installation of [FFTW](http://www.fftw.org) which would include the header file `fftw3.h`. I think I should update the installation instructions to point out that a development installation of [FFTW](http://www.fftw.org) is what does the hard work (the Fourier transforms) in libFTR. You might also need to install cython to compile the c-extensions properly.

You also shouldn't need an `__init__.py` file in the top directory. Try installing things again without the extra `__init__.py` once you've installed FFTW. Then you should be able to use `from FTR.utils import circle_aperture` etc without the problem you see above.

**Comment by slhale** [comment]
I am still getting an error after installing the development version of fftw. 

```
In file included from /tmp/pip-SKsLzM-build/cextern/libFTR/src/ftr.c:9:0:

/tmp/pip-SKsLzM-build/cextern/libFTR/src/ftr.h:18:19: fatal error: fftw3.h: No such file or directory

 #include <fftw3.h>

                   ^

compilation terminated.
```

I also do have Cython installed, so I don't think it's that.

**Comment by alexrudy** [comment]
This is still a problem with your installation of FFTW / shell environment. When a C file includes a header like `#include <fftw3.h>`, it has to know how to find the header file. For instance, I've installed FFTW in `/opt/local/`, so my `CPATH` environment variable (i.e. in your `.bash_profile`) is `CPATH=/opt/local/include`. (You can provide a colon-separated list of places to look, if you need to provide multiple paths). You might then also find that you have to tell the compiler where to find the FFTW library (called `libfftw3.so` or similar). Again, since I use [macports](macports.org), libraries are in `/opt/local/lib`. If I set `LDFLAGS= -L/opt/local/lib` then the compiler knows how to find the FFTW library. Though this step might not be necessary (python might be smart enough to find it on its own).

**Comment by slhale** [comment]
I believe I have now correctly installed FFTW. 
This allows me to install FTR with the following warnings

```
    warning: no files found matching 'CHANGES.rst'
    warning: no files found matching '*.c' under directory '*.pyx'
    warning: no files found matching '*.pxd' under directory '*.pyx'
    warning: no files found matching '*' under directory 'scripts'
    no previously-included directories found matching 'build'
    no previously-included directories found matching 'docs/_build'
    no previously-included directories found matching 'docs/api'
    warning: no previously-included files matching '*.o' found anywhere in distribution
    Installing astropy-package-template-example script to /usr/local/bin
Successfully installed FTR
Cleaning up...
```

But now when I run the code which uses FTR it says that it does not exist

```
Traceback (most recent call last):
  File "phase4.py", line 15, in <module>
    from FTR.FTR.utils import circle_aperture, remove_piston, remove_tiptilt
ImportError: No module named FTR.utils
```

**Comment by alexrudy** [comment]
Great news!

Now the problem stems from that extra `__init__.py` file you (or Rachel) added a while ago. Make sure it isn't there. Then, the way to use FTR in your code is to do imports like `from FTR.utils import ...`, note that I dropped the second `FTR`, as you shouldn't need the name of the module twice to import it properly.

A brief aside about how Python discovers modules: Python looks for folders which contain an **init**.py file. It then decides that those are modules, and it actually runs the `__init__.py` file when you import the folder as a module. You can see that there is some code in [`FTR/__init__.py`](https://github.com/alexrudy/FTR/blob/stable/FTR/__init__.py) which gets run when you first do something like `import FTR`. You should also notice that there is no `__init__.py` file in the top directory. That's because the top directory isn't really a python module. In fact, the top directory is just where the source code is stored. When you install FTR, it will only install things inside the second FTR folder. At the top level, files like `README.md` an `setup.py` get left behind. This is on purpose on python's part, so that you don't end up with unnecessary files/packages installed which you don't want to use in your code. When you added `__init__.py` to the top directory, you turned it into a full python module, so that the original `utils` module was now at `FTR.FTR.utils` and not `FTR.utils`. As you saw above, this didn't really work. That's because FTR isn't pure python code, it includes some C extensions which must be built by the python build system (which you ran using `python setup.py install` or `pip install FTR/`) and so can't be found by just using the source code. In the end, you should never need to add an `__init__.py` file to someone else's source code to make things work, and it will probably just cause confusing bugs like the one above, because you'll bypass python's installation and build system.

**Comment by slhale** [comment]
It works!

Removing the extra FTRs from the imports did it. (It had the double FTRs when I received the code.) 

Thanks a lot for the explanations.
